In [4]:
from pandas_datareader import data
import datetime

In [8]:
start = datetime.datetime(2020,3,1)
end = datetime.datetime(2020,3,31)
df = data.DataReader(name = "GOOG",data_source = "yahoo", start = start, end = end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-03-02,1390.869995,1326.814941,1351.609985,1389.109985,2431500,1389.109985
2020-03-03,1410.150024,1332.000000,1399.420044,1341.390015,2402300,1341.390015
2020-03-04,1388.089966,1343.109985,1359.229980,1386.520020,1913300,1386.520020
2020-03-05,1358.910034,1305.099976,1350.199951,1319.040039,2561300,1319.040039
2020-03-06,1306.219971,1261.050049,1277.060059,1298.410034,2660600,1298.410034
2020-03-09,1254.760010,1200.000000,1205.300049,1215.560059,3365400,1215.560059
2020-03-10,1281.150024,1218.770020,1260.000000,1280.390015,2611400,1280.390015
2020-03-11,1260.959961,1196.069946,1249.699951,1215.410034,2608500,1215.410034
2020-03-12,1193.869995,1113.300049,1126.000000,1114.910034,4226700,1114.910034
2020-03-13,1219.760010,1117.142944,1179.000000,1219.729980,3700100,1219.729980
2020-03-16,1152.266968,1074.439941,1096.000000,1084.329956,4252400,1084.329956
2020-03-17,1130.859985,1056.010010,1093.109985,1119.800049,3861500,1119.800049
2020-03-18,1106.500000,1037.280029,1056.510010,1096.800049,4233400,1096.800049
2020-03-19,1157.969971,1060.108032,1093.050049,1115.290039,3651100,1115.290039
2020-03-20,1143.989990,1065.489990,1135.719971,1072.319946,3601800,1072.319946
2020-03-23,1071.319946,1013.536011,1061.319946,1056.619995,4044100,1056.619995
2020-03-24,1135.000000,1090.619995,1103.770020,1134.459961,3344500,1134.459961
2020-03-25,1148.900024,1086.010010,1126.469971,1102.489990,4081500,1102.489990
2020-03-26,1169.969971,1093.530029,1111.800049,1161.750000,3571700,1161.750000
2020-03-27,1150.670044,1105.910034,1125.670044,1110.709961,3208500,1110.709961
2020-03-30,1151.630005,1096.479980,1125.040039,1146.819946,2574100,1146.819946
2020-03-31,1175.310059,1138.140015,1147.300049,1162.810059,2486400,1162.810059